source 'https://github.com/CocoaPods/Specs.git'

def utilities_pod
  pod 'VOKUtilities', :path => '../'
end

target 'VOKUtilities' do
  utilities_pod

  #nested target block will inherit all settings from parent
  target 'Tests' do
  end

  target 'UITests' do
    pod 'KIF', '~> 3.3'
  end
end

target 'VOKUtilities-tvOS' do
  platform :tvos, '9.0'
  utilities_pod

  target 'Tests-tvOS' do
  end
end

target 'VOKUtilities-OSX' do
  platform :osx, '10.9'
  utilities_pod

  target 'Tests-OSX' do
  end
end
