language: objective-c
osx_image: xcode7.2
env:
  global:
    - SCAN_WORKSPACE="Example/VOKUtilities.xcworkspace"
  matrix:
    # Define the details for each test suite that should be run
    - SCAN_SCHEME="VOKUtilities-Example" SCAN_SDK="iphonesimulator"
    - SCAN_SCHEME="VOKUtilities-tvOS"    SCAN_SDK="appletvsimulator"
    - SCAN_SCHEME="VOKUtilities-OSX"     SCAN_SDK="macosx"
script: bundle exec scan
after_script:
  - bundle exec pod lib lint
git:
  depth: 10000  # For the auto-incrementing build number script to work, we need to clone with a basically-infinite depth.
cache:
  - bundler  # After main-repo builds, save the "bundler" (local Ruby gems) stuff to cache for future builds.
